import logging


def function1():
    logging.info("This is in func1.py")


def raiseException():
    raise Exception("An exception in func1.py")
